export const authconstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
}
export const userconstants = {
    SIGHNUP_REQUEST: "SIGHNUP_REQUEST",
    SIGHNUP_SUCCESS: "SIGHNUP_SUCCESS",
    SIGHNUP_FAILURE: "SIGHNUP_FAILURE",
}